# Generated by Django 3.0.5 on 2020-04-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0002_power_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='levels',
            new_name='level',
        ),
    ]
