# Generated by Django 3.0.5 on 2020-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0004_metahuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahuman',
            name='ally',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
