# Generated by Django 3.0.5 on 2020-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0005_auto_20200430_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(max_length=4000)),
                ('headquarter', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.AddField(
            model_name='metahuman',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
