# Generated by Django 3.0.6 on 2020-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0010_auto_20200506_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metahuman',
            options={'verbose_name': 'Metahumano', 'verbose_name_plural': 'Metahumanos'},
        ),
        migrations.AlterField(
            model_name='metahuman',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
